In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [21]:
input_path= "/Users/sayarsamanta/Documents/GitHub/Data-Science-Projects/Classification Problem/Logistic Regression/Breast Cancer/Data/"

In [22]:
data = pd.read_csv(input_path+'breast_cancer.csv')

In [23]:
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1                3                1        1      2  
1           10                3                2        1      2  
2            2                3                1        1      2  
3            4                3                7        1      2  
4            1                3                1        1      2

In [24]:
data.describe().T

count          mean            std      min  \
Sample code number           683.0  1.076720e+06  620644.047655  63375.0   
Clump Thickness              683.0  4.442167e+00       2.820761      1.0   
Uniformity of Cell Size      683.0  3.150805e+00       3.065145      1.0   
Uniformity of Cell Shape     683.0  3.215227e+00       2.988581      1.0   
Marginal Adhesion            683.0  2.830161e+00       2.864562      1.0   
Single Epithelial Cell Size  683.0  3.234261e+00       2.223085      1.0   
Bare Nuclei                  683.0  3.544656e+00       3.643857      1.0   
Bland Chromatin              683.0  3.445095e+00       2.449697      1.0   
Normal Nucleoli              683.0  2.869693e+00       3.052666      1.0   
Mitoses                      683.0  1.603221e+00       1.732674      1.0   
Class                        683.0  2.699854e+00       0.954592      2.0   

                                  25%        50%        75%         max  
Sample code number           877617.0  1171795.0  1238705.0  13454352.0  
Clump Thickness                   2.0        4.0        6.0        10.0  
Uniformity of Cell Size           1.0        1.0        5.0        10.0  
Uniformity of Cell Shape          1.0        1.0        5.0        10.0  
Marginal Adhesion                 1.0        1.0        4.0        10.0  
Single Epithelial Cell Size       2.0        2.0        4.0        10.0  
Bare Nuclei                       1.0        1.0        6.0        10.0  
Bland Chromatin                   2.0        3.0        5.0        10.0  
Normal Nucleoli                   1.0        1.0        4.0        10.0  
Mitoses                           1.0        1.0        1.0        10.0  
Class                             2.0        2.0        4.0         4.0

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sample code number           683 non-null    int64
 1   Clump Thickness              683 non-null    int64
 2   Uniformity of Cell Size      683 non-null    int64
 3   Uniformity of Cell Shape     683 non-null    int64
 4   Marginal Adhesion            683 non-null    int64
 5   Single Epithelial Cell Size  683 non-null    int64
 6   Bare Nuclei                  683 non-null    int64
 7   Bland Chromatin              683 non-null    int64
 8   Normal Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB


In [26]:
type(data)

pandas.core.frame.DataFrame

In [27]:
data.Class.value_counts()

2    444
4    239
Name: Class, dtype: int64

In [28]:
data = data.drop('Sample code number',axis=1)

In [29]:
data

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
0                  5                        1                         1   
1                  5                        4                         4   
2                  3                        1                         1   
3                  6                        8                         8   
4                  4                        1                         1   
..               ...                      ...                       ...   
678                3                        1                         1   
679                2                        1                         1   
680                5                       10                        10   
681                4                        8                         6   
682                4                        8                         8   

     Marginal Adhesion  Single Epithelial Cell Size  Bare Nuclei  \
0                    1                            2            1   
1                    5                            7           10   
2                    1                            2            2   
3                    1                            3            4   
4                    3                            2            1   
..                 ...                          ...          ...   
678                  1                            3            2   
679                  1                            2            1   
680                  3                            7            3   
681                  4                            3            4   
682                  5                            4            5   

     Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0                  3                1        1      2  
1                  3                2        1      2  
2                  3                1        1      2  
3                  3                7        1      2  
4                  3                1        1      2  
..               ...              ...      ...    ...  
678                1                1        1      2  
679                1                1        1      2  
680                8               10        2      4  
681               10                6        1      4  
682               10                4        1      4  

[683 rows x 10 columns]

In [30]:
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [31]:
X

array([[ 5,  1,  1, ...,  3,  1,  1],
       [ 5,  4,  4, ...,  3,  2,  1],
       [ 3,  1,  1, ...,  3,  1,  1],
       ...,
       [ 5, 10, 10, ...,  8, 10,  2],
       [ 4,  8,  6, ..., 10,  6,  1],
       [ 4,  8,  8, ..., 10,  4,  1]])

In [32]:
y

array([2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 4, 4,
       2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4, 4, 4, 4, 4, 2,
       4, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4, 2, 4,
       4, 2, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 2, 4,
       4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2, 2, 4, 2,
       2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2,
       4, 4, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2,
       2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2,
       2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2, 2, 4, 4, 4, 4, 2,
       4, 4, 2, 4, 4, 4, 2, 4, 2, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 4, 4, 2,
       2, 4, 2, 4, 4, 4, 2, 2, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 2, 4, 2,
       4, 4, 2, 2, 2, 2, 4, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 2, 2, 4, 4, 2,
       2, 4, 4, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2, 2, 4,

In [33]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=1)

In [34]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [35]:
X_train

array([[-1.21629973, -0.70863282, -0.75174943, ..., -0.99312055,
        -0.62911518, -0.36280962],
       [-0.15298932, -0.70863282, -0.41233523, ..., -0.58305787,
        -0.62911518, -0.36280962],
       [ 0.91032108,  0.28358232,  1.2847358 , ...,  1.46725553,
         1.02611078, -0.36280962],
       ...,
       [ 1.97363148,  0.94505909,  0.26649318, ..., -0.17299519,
        -0.29806999,  0.8241458 ],
       [-0.86186292, -0.70863282, -0.75174943, ..., -0.17299519,
        -0.62911518, -0.36280962],
       [ 0.20144748,  0.28358232,  0.26649318, ...,  0.64713017,
         1.02611078, -0.36280962]])

In [36]:
X_test

array([[ 0.20144748, -0.70863282, -0.75174943, ..., -0.58305787,
        -0.62911518, -0.36280962],
       [-1.21629973, -0.70863282, -0.75174943, ..., -0.17299519,
        -0.62911518, -0.36280962],
       [-0.15298932, -0.70863282, -0.75174943, ..., -0.17299519,
        -0.62911518, -0.36280962],
       ...,
       [-0.15298932, -0.70863282, -0.75174943, ..., -0.17299519,
        -0.62911518, -0.36280962],
       [-0.15298932, -0.70863282, -0.75174943, ..., -0.58305787,
        -0.62911518, -0.36280962],
       [-0.50742612, -0.70863282, -0.75174943, ..., -0.58305787,
        -0.62911518, -0.36280962]])

In [37]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [38]:
print(classifier.predict(sc.transform([[5,1,1,1,2,1,3,1,1]])))

[2]


In [39]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 4]
 [2 2]
 [4 4]

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[111   0]
 [  3  57]]


0.9824561403508771